main: com.cgms.minecraft.spigot.plugin.MinecraftEmpiresPlugin # The full path to your main class
name: MinecraftEmpiresPlugin # The name of your plugin
version: 1.0 # The version of your plugin
author: Cow Goes Moo Software # Your name or the author's name
description: Minecraft epires spigot plugin # A brief description
api-version: 1.21 # The API version your plugin uses, helps with compatibility
depend: [Citizens]

commands:
  npc-gui:
    description: "Opens a the NPC allocation GUI"
    usage: "/npc-gui"
    permission:
