/*
 * Copyright (c) 2026
 * SPDX-License-Identifier: MIT
 */

package com.cgms.minecraft.empires.dto;

public enum AiEventType
{
    UNDER_ATTACK,
    BATTLE_STARTED,
    BATTLE_ENDED,
    BATTLE_UPDATE,
    ATTACK_LOCATION,
    MOVEMENT_UPDATE,
    MOVEMENT_COMPLETE,
    BUILDING_UPDATE,
    BUILDING_DESTROYED,
    BUILDING_CREATED,
    BUILDING_REPAIRED,
    UNIT_CREATED,
    UNIT_DESTROYED,
    PLAYER_ENTERED_TERRITORY,
    PLAYER_LEFT_TERRITORY,
    PLAYER_DECLARED_WAR,
    PLAYER_DECLARED_PEACE
}
