logging:
  level:
    root: ERROR
    com.cgms: DEBUG
spring:
  server: 2224
  activemq:
    broker-url: "tcp://${ACTIVE_MQ_HOST}:${ACTIVE_MQ_PORT}"
    user: "${ACTIVE_MQ_USERNAME}"
    password: "${ACTIVE_MQ_PASSWORD}"
  ai:
    google:
      genai:
        api-key: "${AI_API_KEY:}"